export const financialSenders = [
    "bank",
    "chase",
    "capitalone",
    "capital one",
    "americanexpress",
    "american express",
    "amex",
    "citi",
    "citibank",
    "wellsfargo",
    "wells fargo",
    "bankofamerica",
    "bank of america",
    "bofa",
    "usbank",
    "u.s. bank",
    "discover",
    "synchrony",
    "barclays",
    "paypal",
    "venmo",
    "stripe",
    "square",
    "robinhood",
    "fidelity",
    "vanguard",
    "schwab",
    "etrade",
    "e-trade",
    "coinbase",
    "binance",
    "irs",
    "turbotax",
    "intuit"
];
